export const commonMistakes = [
  { m: "yuo", c: "you" },
  { m: "everyday", c: "every day" },
  { m: "sometime", c: "sometimes" },
  { m: "dont", c: "don't" },
  { m: "rarelfy", c: "rarely" },
  { m: "converselyt", c: "conversely" },
  { m: "tech", c: "teach" },
  { m: "confuse", c: "confused" },
  { m: "studing", c: "studying" },
  { m: "easyer", c: "easier" },
  { m: "nobodye", c: "nobody" },
  { m: "alot", c: "a lot" },
  { m: "belive", c: "believe" },
  { m: "recive", c: "receive" },
  { m: "thier", c: "their" },
  { m: "truely", c: "truly" },
  { m: "definately", c: "definitely" },
  { m: "occured", c: "occurred" },
  { m: "untill", c: "until" },
];
