export const forensicRules = [
  // Spelling & Phonetics (RED)
  { regex: /\bfroot\b/gi, type: "spelling", suggestion: "fruit", exp: "Phonetic spelling anomaly." },
  { regex: /\bwheather\b/gi, type: "spelling", suggestion: "weather", exp: "Semantic confusion (weather vs whether)." },
  { regex: /\bTheir\s+was\b/gi, type: "spelling", suggestion: "There was", exp: "Homophone confusion (There/Their)." },
  { regex: /\bpeples\b/gi, type: "spelling", suggestion: "people", exp: "Irregular plural spelling error." },
  { regex: /\bshoping\b/gi, type: "spelling", suggestion: "shopping", exp: "Missing double consonant." },
  { regex: /\btrys\b/gi, type: "spelling", suggestion: "tries", exp: "Incorrect verb suffix." },
  { regex: /\binsted\b/gi, type: "spelling", suggestion: "instead", exp: "Spelling anomaly." },
  { regex: /\bfreind\b/gi, type: "spelling", suggestion: "friend", exp: "I before E error." },
  { regex: /\bcrazyness\b/gi, type: "spelling", suggestion: "craziness", exp: "Suffix spelling error." },
  { regex: /\bexpensve\b/gi, type: "spelling", suggestion: "expensive", exp: "Missing vowel." },
  { regex: /\bgrocerie\b/gi, type: "spelling", suggestion: "grocery", exp: "Spelling anomaly." },
  { regex: /\brelized\b/gi, type: "spelling", suggestion: "realized", exp: "Missing vowel." },
  { regex: /\bimportent\b/gi, type: "spelling", suggestion: "important", exp: "Vowel confusion." },
  { regex: /\bgeting\b/gi, type: "spelling", suggestion: "getting", exp: "Missing double consonant." },
  { regex: /\bsoked\b/gi, type: "spelling", suggestion: "soaked", exp: "Spelling anomaly." },
  { regex: /\btotaly\b/gi, type: "spelling", suggestion: "totally", exp: "Missing double consonant." },
  { regex: /\bfinaly\b/gi, type: "spelling", suggestion: "finally", exp: "Missing double consonant." },
  { regex: /\bcitys\b/gi, type: "spelling", suggestion: "cities", exp: "Plural spelling anomaly." },
  { regex: /\beverybodys\b/gi, type: "spelling", suggestion: "everybody", exp: "Possessive/Plural confusion." },

  // Grammar: Pronoun-Verb Agreement & Case (BLUE)
  { regex: /\bMe\s+and\s+(\w+)\s+is\b/gi, type: "grammar", suggestion: "$1 and I are", exp: "Compound subject case and agreement error." },
  { regex: /\bthem\b/gi, type: "grammar", suggestion: "they", exp: "Objective pronoun used as subject." },
  { regex: /\bhim\b(?=\s+(?:is|was|went|go|goes|want|wants|thinks|knows|cryed|cried|has|had|did))/gi, type: "grammar", suggestion: "he", exp: "Objective pronoun used as subject." },
  { regex: /\bher\b(?=\s+(?:is|was|went|go|goes|want|wants|thinks|knows|don't|doesn't|has|had|did))/gi, type: "grammar", suggestion: "she", exp: "Objective pronoun used as subject." },
  { regex: /\bus\b(?=\s+(?:is|was|went|go|goes|want|wants|thinks|knows|drinked|drank|has|had|did))/gi, type: "grammar", suggestion: "we", exp: "Objective pronoun used as subject." },
  { regex: /\bHer\s+don't\b/gi, type: "grammar", suggestion: "She doesn't", exp: "Subject-case and auxiliary agreement error." },
  { regex: /\bMe\s+is\b/gi, type: "grammar", suggestion: "I am", exp: "Subject-case and agreement mismatch." },
  { regex: /\bia\s+m\b/gi, type: "grammar", suggestion: "I am", exp: "Subject-auxiliary typographic anomaly." },
  { regex: /\bi\s+am\s+([a-z]{2,})(?<!ing|being|doing|going)\b/gi, type: "grammar", suggestion: "I am $1ing", exp: "Incorrect present continuous form." },
  { regex: /\bi\b/g, type: "grammar", suggestion: "I", exp: "First-person pronoun must always be capitalized." },
  { regex: /\bMe\s+(\w+)\b/gi, type: "grammar", suggestion: "I $1", exp: "Subject-case pronoun error." },
  { regex: /\bda\b/gi, type: "grammar", suggestion: "the", exp: "Non-standard article usage." },
  { regex: /\bdem\s+dont\b/gi, type: "grammar", suggestion: "they don't", exp: "Subject-case and auxiliary agreement error." },
  { regex: /\bu\s+no\s+has\b/gi, type: "grammar", suggestion: "you don't have", exp: "Subject-case and verb agreement error." },
  { regex: /\bwanna\b/gi, type: "grammar", suggestion: "want to", exp: "Colloquial contraction is non-academic." },
  { regex: /\bgunna\b/gi, type: "grammar", suggestion: "going to", exp: "Colloquial contraction is non-academic." },
  { regex: /\bgetted\b/gi, type: "syntax", suggestion: "got", exp: "Irregular verb form anomaly." },
  { regex: /\bkeeped\b/gi, type: "syntax", suggestion: "kept", exp: "Irregular verb form anomaly." },
  { regex: /\b(it|this)\s+are\b/gi, type: "grammar", suggestion: "$1 is", exp: "Singular agreement error." },
  { regex: /\bapples\s+is\b/gi, type: "grammar", suggestion: "apples are", exp: "Plural agreement error." },

  // Syntax: Tense & Verb Forms (GREEN)
  { regex: /\b(goes|go)\b(?=.*?\byesterday\b)/gi, type: "syntax", suggestion: "went", exp: "Tense mismatch with 'yesterday'." },
  { regex: /\b(is|are)\b(?=.*?\byesterday\b)/gi, type: "syntax", suggestion: "was", exp: "Tense mismatch with 'yesterday'." },
  { regex: /\bIf\s+I\s+was\s+you\b/gi, type: "syntax", suggestion: "If I were you", exp: "Subjunctive mood error." },
  { regex: /\bI\s+will\s+not\s+bought\b/gi, type: "syntax", suggestion: "I would not buy", exp: "Modal-tense mismatch." },
  { regex: /\bbuyed\b/gi, type: "syntax", suggestion: "bought", exp: "Irregular verb past form error." },
  { regex: /\bdrinked\b/gi, type: "syntax", suggestion: "drank", exp: "Irregular verb past form error." },
  { regex: /\bsayed\b/gi, type: "syntax", suggestion: "said", exp: "Irregular verb past form error." },
  { regex: /\bcryed\b/gi, type: "syntax", suggestion: "cried", exp: "Spelling/Verb form error." },
  { regex: /\bhas\s+goed\b/gi, type: "syntax", suggestion: "has gone", exp: "Irregular verb anomaly." },
  { regex: /\blefted\b/gi, type: "syntax", suggestion: "left", exp: "Irregular verb error." },
  { regex: /\bsitted\b/gi, type: "syntax", suggestion: "sat", exp: "Irregular verb error." },
  { regex: /\bfinded\b/gi, type: "syntax", suggestion: "found", exp: "Irregular verb error." },
  { regex: /\bI\s+seen\b/gi, type: "syntax", suggestion: "I saw", exp: "Simple past vs past participle error." },
  { regex: /\bus\s+drinked\b/gi, type: "syntax", suggestion: "we drank", exp: "Subject-case and verb form error." },
  { regex: /\bhim\s+cryed\b/gi, type: "syntax", suggestion: "he cried", exp: "Subject-case and verb form anomaly." },

  // Tone & Sophistication (PURPLE)
  { regex: /\b(is|was|were|been|being)\s+\w+ed\s+by\b/gi, type: "tone", suggestion: "Use active voice", exp: "Passive voice weakens scholarly authority." },
  { regex: /\bThe\s+\w+(tion|ment|ity|ance|ence)\s+of\b/gi, type: "diction", suggestion: "Simplify structure", exp: "Nominalization can make academic writing 'sticky'." },
  { regex: /\b(seems\s+to|appears\s+to|could\s+possibly|may\s+be|might\s+be)\b/gi, type: "tone", suggestion: "Use assertive language", exp: "Over-hedging reduces the impact of findings." },
  { regex: /\bthink\b/gi, type: "tone", suggestion: "Assert", exp: "Use assertive verbs to increase scholarly authority." },
  { regex: /\bbelieve\b/gi, type: "tone", suggestion: "Contend", exp: "Academic 'Contend' is more rigorous than 'Believe'." },
  { regex: /\bmaybe\b/gi, type: "tone", suggestion: "Potentially", exp: "Use formal probability markers." },
  { regex: /\bguess\b/gi, type: "tone", suggestion: "Hypothesize", exp: "Professional research requires hypothesizing." },

  // Diction & Modifiers (ORANGE)
  { regex: /\ba\s+[aeiou]\w+/gi, type: "diction", suggestion: "an", exp: "Incorrect article usage before vowel sound." },
  { regex: /\ban\s+[^aeiou]\w+/gi, type: "diction", suggestion: "a", exp: "Incorrect article usage before consonant sound." },
  { regex: /\bmore\s+(\w+er)\b/gi, type: "diction", suggestion: "$1", exp: "Double comparative error." },
  { regex: /\bmost\s+(\w+est)\b/gi, type: "diction", suggestion: "$1", exp: "Double superlative error." },
  { regex: /\bthen\b(?=.*?\bthan\b)/gi, type: "diction", suggestion: "than", exp: "Comparison word confusion." },
  { regex: /\bto\s+much\b/gi, type: "diction", suggestion: "too much", exp: "Adverbial 'too' required." },
  { regex: /\bsourly\b/gi, type: "diction", suggestion: "sour", exp: "Adjective/Adverb confusion." },
  { regex: /\bthirstly\b/gi, type: "diction", suggestion: "thirsty", exp: "Incorrect adjective form." },
  { regex: /\bbrokenly\b/gi, type: "diction", suggestion: "broken", exp: "Incorrect adjective form." },
  { regex: /\b(very|extremely|really|quite|totally|completely)\b/gi, type: "diction", suggestion: "Omit", exp: "Weak adverbs reduce academic rigor." },

  // Technical & Symbol Anomalies (RED)
  { regex: /([a-z]+)[^a-z\s0-9.?!,;:'"\-]+([a-z]+)/gi, type: "spelling", suggestion: "$1$2", exp: "Technical character noise detected inside word structure." },
  { regex: /\broboticsc\b/gi, type: "spelling", suggestion: "robotics", exp: "Common technical typo." },
];
